abz_automations/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

website/urls.py
from django.urls import path

from .views import HomeView, OrderView, getformdata, add_to_basket,basket_update,basket_delete, confirm_basket

app_name = 'website'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('order/', OrderView.as_view(), name='order'),
    path('formdata/',getformdata,name='getformdata'),
    
    path('cart/add/', add_to_basket, name='cart-add'),
    path('cart/update/', basket_update, name='cart-update'),
    path('cart/delete/', basket_delete, name='cart-delete'), 
    path('cart/confirm/', confirm_basket, name='cart-confirm'), 



]

website/models.py
import uuid
from django.db import models
from utils.constants import TINY_STR_LEN, SHORT_STR_LEN, LONG_STR_LEN

from location_field.models.plain import PlainLocationField

from django.db import models
from utils.constants import TINY_STR_LEN, SHORT_STR_LEN, LONG_STR_LEN, ICON_CHOICES


# Create your models here.


def icon_image_directory(instance, filename):
    return '/'.join(['images', 'team-member', str(instance.first_name), filename])


def product_image_directory(instance, filename):
    return '/'.join(['images', 'team-member', str(instance.name), filename])


class TeamMember(models.Model):
    first_name = models.CharField(max_length=SHORT_STR_LEN)
    other_names = models.CharField(
        max_length=SHORT_STR_LEN, null=True, blank=True)
    last_name = models.CharField(max_length=SHORT_STR_LEN)
    role = models.CharField(max_length=SHORT_STR_LEN)
    image = models.ImageField(upload_to=icon_image_directory)
    linked_in = models.URLField()
    email = models.EmailField()

    def __str__(self):
        return self.first_name


class Metric(models.Model):
    name = models.CharField(max_length=SHORT_STR_LEN)
    count = models.IntegerField()
    icon = models.CharField(max_length=SHORT_STR_LEN,
                            choices=ICON_CHOICES, default="icofont-water-drop")

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=SHORT_STR_LEN)
    description = models.TextField()
    image = models.ImageField(upload_to=product_image_directory)

    def __str__(self):
        return self.name


class ProductModel(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="product_models")
    name = models.CharField(max_length=SHORT_STR_LEN)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    available = models.BooleanField(default=True,)

    def __str__(self):
        return f"{self.product} - {self.name}"


class ProductModelFeature(models.Model):
    product_model = models.ForeignKey(
        ProductModel, on_delete=models.CASCADE, related_name="product_model_features")
    description = models.CharField(max_length=LONG_STR_LEN)

    def __str__(self):
        return self.description


class Service(models.Model):
    name = models.CharField(max_length=SHORT_STR_LEN)
    description = models.CharField(max_length=LONG_STR_LEN, null=True)
    # price = models.DecimalField(max_digits=6, decimal_places=2)
    icon = models.CharField(max_length=SHORT_STR_LEN,
                            choices=ICON_CHOICES, default="icofont-water-drop")

    def __str__(self):
        return self.name


class Basket(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    customer_name = models.CharField(max_length=SHORT_STR_LEN)
    customer_email = models.EmailField()
    # https://django-location-field.readthedocs.io/en/latest/tutorials.html#using-django-location-field-in-the-django-admin
    #! location = PlainLocationField(based_fields=['city'], zoom=7)
    customer_phone_number = models.CharField(max_length=SHORT_STR_LEN)
    date_ordered = models.DateTimeField(auto_now_add=True)
    extra_info = models.TextField(blank=True, null=True)

    def __str__(self):
        return str(self.id)


class ServiceRequest(models.Model):
    # total_amount = models.DecimalField(max_digits=6, decimal_places=2)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    basket = models.ForeignKey(
        Basket, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.service.name


class ProductOrder(models.Model):
    # product = models.ForeignKey(Product,on_delete=models.CASCADE)
    # unit_price = models.DecimalField(max_digits=6, decimal_places=2)
    product_model = models.ForeignKey(ProductModel, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    total_amount = models.DecimalField(max_digits=6, decimal_places=2)
    basket = models.ForeignKey(
        Basket, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.product_model.name

    def save(self, *args, **kwargs):
        self.total_amount = self.product_model.price * self.quantity
        return super(ProductOrder, self).save(*args, **kwargs)

website/views.py
from pprint import pprint
from django.shortcuts import render,redirect
from django.http import JsonResponse
from django.views.generic import TemplateView, ListView, View
from django.contrib.auth import get_user_model
from django.conf import settings
from django.contrib import messages

from utils.mailing import Util as MailUtil

from .models import Basket, Metric, ProductModel, ProductOrder, ServiceRequest, TeamMember, Product, Service

from .basket import Basket as SessionBasket
# Create your views here.
user = get_user_model()

class HomeView(ListView):
    model = Metric
    context_object_name = "metrics"
    template_name = 'website/index.html'

    def get_context_data(self, **kwargs) :
        context = super(HomeView, self).get_context_data(**kwargs)
        context.update({
            'team_member_list': TeamMember.objects.all(),
            'product_list': Product.objects.all(),
            'service_list': Service.objects.all(),

        })
        return context


def getformdata(request):
    data = request.POST
    email_body = data['name'] + ' '+ 'response email' + ' '+ data['email'] + '\n' + data['message']
    data = {'email_body': email_body, 'to_email': settings.EMAIL_HOST_USER,
                'email_subject': data['subject']}
    MailUtil.send_email(data)
    print(data)
    
    # messages.info(request, 'Your message has been successfully sent!')
    return redirect('website:home')


class OrderView(TemplateView):
    template_name = 'website/order.html'


def add_to_basket(request):
    session_basket = SessionBasket(request)
    
    if request.method == 'POST':
        # check the type of order and add to the appropriate basket section
        order_type = request.POST.get('order_type')

        if order_type == "product_order":
            product_model_id = int(request.POST.get('product_model_id'))

            # check if product_model is already in basket
            if str(product_model_id) in session_basket.basket['product_orders']:
                print("error here")
                return JsonResponse({"error": "already added"}, status=400)


            # create product order and add to basket 
            product_model = ProductModel.objects.get(pk=product_model_id)
            session_basket.add_product_model(product_model=product_model)
        
        elif order_type == "service_request":
            service_id = int(request.POST.get('service_id'))

            print(str(service_id))
            print(session_basket.basket['service_requests'])
            print(str(service_id) in session_basket.basket['service_requests'])
            # check if service is already in basket
            if str(service_id) in session_basket.basket['service_requests']:
                print("error here")
                return JsonResponse({"error": "already added"}, status=400)

            # create service request and add to basket 
            service = Service.objects.get(pk=service_id)
            session_basket.add_service(service=service)
        
        pprint(session_basket.basket)
        return JsonResponse({
            "basket": session_basket.basket,
            "basket_quantity": session_basket.__len__()
            })


        

        # basket_length = product_order.basket.product_order_set.count() + product_order.basket.service_request_set.count()

        # # return length of basket
        # return JsonResponse({
        #     'basket_length': basket_length,
        # })

def basket_update(request):
    session_basket = SessionBasket(request)
    if request.method == 'POST':
        product_model_id = int(request.POST.get('product_model_id'))
        product_qty = int(request.POST.get('productqty'))
        session_basket.update_product_order(product_model_id=product_model_id,quantity=product_qty)
        print(session_basket.basket['product_orders'])
        print(product_model_id)
        print(product_qty)
        # get the length of the items in the basket
        basket_quantity = session_basket.__len__()
        # basket_total = basket.get_total_price()
        response = JsonResponse({'basket_quantity':basket_quantity})#'total':basket_total
        return response


def basket_delete(request):
    session_basket = SessionBasket(request)
    if request.method == 'POST':
        # check the type of order and add to the appropriate basket section
        order_type = request.POST.get('order_type')

        if order_type == "product_order":
            product_model_id = int(request.POST.get('product_model_id'))

            # check if product_model is in basket
            if not str(product_model_id) in session_basket.basket['product_orders']:
                print("error here")
                return JsonResponse({"error": "no such product order"}, status=400)

            session_basket.delete_product_order(product_model_id=product_model_id)
            basket_quantity = session_basket.__len__()
            basket_total = session_basket.get_total_price()
            
            response = JsonResponse({
                'basket_quantity':basket_quantity, 
                'total':basket_total
                })
            return response
        
        elif order_type == "service_request":
            service_id = int(request.POST.get('service_id'))

            # check if product_model is in basket
            if not str(service_id) in session_basket.basket['service_requests']:
                print("error here")
                return JsonResponse({"error": "no such service request"}, status=400)

            session_basket.delete_service_request(service_id=service_id)
            basket_quantity = session_basket.__len__()
            basket_total = session_basket.get_total_price()
            
            response = JsonResponse({
                'basket_quantity':basket_quantity, 
                'total':basket_total
                })
            return response


def confirm_basket(request):
    session_basket = SessionBasket(request)
    if request.method == 'POST':
        # creating the basket item
        customer_name = request.POST.get('customer_name')
        customer_email = request.POST.get('customer_email')
        customer_phone_number = request.POST.get('customer_phone_number')
        extra_info = request.POST.get('extra')
        
        current_basket = Basket.objects.create(
            customer_name = customer_name,
            customer_email = customer_email,
            customer_phone_number = customer_phone_number,
            extra_info = extra_info
        )
        current_basket.save()

        for i,v in session_basket.basket['product_orders'].items():
            product_model = ProductModel.objects.get(id = int(i))
            quantity = v['quantity']
            total_amount = v['price']
            basket = current_basket

            product_order = ProductOrder.objects.create(
                product_model = product_model,
                quantity = quantity,
                total_amount = total_amount,
                basket = basket
            )
            product_order.save()

        for i,v in session_basket.basket['service_requests'].items():
            service = Service.objects.get(id = int(i))

            service_create=ServiceRequest.objects.create(
                service = service,
                basket = basket
            )
            service_create.save()
        message = (
        "Hello Boss\n" +
        f"You just received an order from {customer_name}\n" +
        "Login to your dashboard to view more details\n\n" +
        "Have a nice day"
    )

        email_body = message
        data = {'email_body': email_body, 'to_email': settings.EMAIL_HOST_USER,
                'email_subject': 'Order Placement'}
        MailUtil.send_email(data)

        session_basket.clear(request)

        response = JsonResponse({})
        return response





        

website/templates/website/index.html
{% load static %}
{% load basket_length %}


<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>ABZ AUTOMATIONS</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  {% comment %} Favicons {% endcomment %}
  <link href="{% static 'website/img/favicon.png' %}" rel="icon">
  <link href="{% static 'website/img/apple-touch-icon.png' }" rel="apple-touch-icon">

  {% comment %} Google Fonts {% endcomment %}
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    
    {% comment %} jquery {% endcomment %}
  <script src="{% static 'website/vendor/jquery/jquery.min.js' %}"></script>


  {% comment %} Template Main CSS File {% endcomment %}
  <link href="{% static 'website/css/style2.css' %}" rel="stylesheet">

  {% comment %} font awesome {% endcomment %}
  <script src="https://kit.fontawesome.com/546832c0ab.js" crossorigin="anonymous"></script>

  
</head>

<body>
  <section class="header">

    <nav>
      <div class="site-header">
        <div  class="logo-img"><img src="{% static 'website/img/logo.png' %}" alt="logo"></div>
        ABZ-AUTOMATIONS
      </div>

      <div >
        <ul class="nav-items">
          <li><a href="#about">Blog</a></li>
          <li><a href="#products-and-services">Services</a></li>
           <li><a href="#products">Products</a></li> 
          <li><a href="#recents">Projects</a></li>
          <li><a href="#team">Team</a></li>
        </ul>
      </div>

      <div class="cart">
        <a>
          <i class="icofont-shopping-cart icofont-2x"></i> 
          <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-primary" id="basket-quantity">
            {{request.session.skey|basket_length}}
          </span>
        </a>
      </div>
    </nav>
  </section>
</body>


website/templates/website/order.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Order - ABZ AUTOMATIONS</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'website/img/favicon.png' %}" rel="icon">
  <link href="{% static 'website/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'website/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'website/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'website/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'website/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'website/vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'website/vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'website/css/style.css' %}" rel="stylesheet">

  
</head>

<body>

   <!-- ======= Top Bar ======= -->
   <div id="topbar" class="d-none d-lg-flex align-items-center fixed-top">
    <div class="container d-flex">
      <div class="contact-info me-auto">
        <i class="icofont-envelope"></i> <a href="abzautomations@gmail.com">abzautomations@gmail.com</a>
        <i class="icofont-phone"></i> +233 50 159 1370
      </div>
      <div class="social-links">
        <a href="https://twitter.com/abz_automations" class="twitter"><i class="icofont-twitter"></i></a>
        <a href="https://web.facebook.com/1Abzautomations" target="_blank" rel="noopener noreferrer" class="facebook"><i class="icofont-facebook"></i></a>
        <a href="https://www.instagram.com/abz_automations/" target="_blank" rel="noopener noreferrer" class="instagram"><i class="icofont-instagram"></i></a>
        <a href="https://www.youtube.com/channel/UClOn2TaH7U78kf0NlVFLRZg" target="_blank" rel="noopener noreferrer" class="youtube"><i class="icofont-youtube"></i></a>
        <a href="https://Wa.me/+233501591370" target="_blank" rel="noopener noreferrer"class="whatsapp"><i class="icofont-whatsapp"></i></i></a>
        <a  href="https://www.linkedin.com/company/19127501/" target="_blank" rel="noopener noreferrer" class="linkedin"><i class="icofont-linkedin"></i></i></a>
      </div>
    </div>
  </div>

   <!-- ======= Header ======= -->
   <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">
      <a href="{% url "website:home" %}" class="logo-img"><img src="{% static 'website/img/logo.jpeg' %}" alt="logo"></a>
      <h1 class="logo me-auto"><a href="{% url 'website:home' %}">ABZ AUTOMATIONS</a></h1>
      
      

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          {% comment %} <li class="active"><a href="{% url 'website:home' %}">Home</a></li> {% endcomment %}
          <li><a href="{% url 'website:home' %}#about">About</a></li>
          <li><a href="{% url 'website:home' %}#products-and-services">Services</a></li>
          <li><a href="{% url 'website:home' %}#products">Products</a></li>
          <li><a href="{% url 'website:home' %}#recents">Projects</a></li>
          <li><a href="{% url 'website:home' %}#pricing">Pricing</a></li>
          <li><a href="{% url 'website:home' %}#team">Team</a></li>
          <li><a href="{% url 'website:home' %}#contact">Contact</a></li>

        </ul>
      </nav><!-- .nav-menu -->

    </div>
  </header><!-- End Header -->


  <main id="main" data-aos="fade-up">

    <!-- ======= Breadcrumbs Section ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Place Order</h2>
          <ol>
            <li><a href="{% url 'website:home' %}">Home</a></li>
            <li><a href="{% url 'website:order' %}">Order</a></li>
            <li>Place Order</li>
          </ol>
        </div>

      </div>
    </section><!-- Breadcrumbs Section -->

    <!-- ======= Order Details Section ======= -->
    <section id="contact" class="contact" >
      <div class="container" data-aos="fade-up">
      <div class="col-lg-8">
        <form action="send{% url 'website:order' %}" method="post" role="form" class="php-email-form" enctype="multipart/form-data">
        <div class="row">
                <div class="col form-group">
                  <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" /> 
                </div>
                <div class="col form-group">
                  <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                  
                </div>
              </div>

            
              <div class="row">
                <div class="col form-group">
                  <input type="text" name="location" class="form-control" id="location" placeholder="Location" data-rule="minlen:" data-msg="Please enter your location" />
                  
                </div>
                <div class="col form-group">
                  <input type="number" class="form-control" name="phone" id="phone" placeholder="Phone" data-rule="minlen:4" data-msg="Please enter a valid phone number" />
                  
                </div>
              </div>
              

             <div class="row">
              <div class="col form-group">
                <label for="model">Select preffered model</label>
                    <select class="form-control" id="model">
                       <option></option>
                       <option>MODEL WLC 210</option>
                       <option>MODEL WLC 210P</option>
                       <option>MODEL WLC 210S</option>
                       <option>MODEL WLC 210X</option>
                       
                    </select>
              </div>
              <div class="col form-group">
                  <label for="image">Upload picture of tank</label>
                 <input type="file" class="form-control form-control-file" name="image" id="image">
                </div>
              </div>
              
              <div class="row">
                <div class="col form-group">
                  <input type="number" name="tank" class="form-control" id="tank" placeholder="Number of Tanks" data-rule="minlen:4" data-msg="Please enter at least 4 chars" /> 
                </div>
                <div class="col form-group">
                  <input type="number" class="form-control" name="pump" id="pump" placeholder="Number of Pumps" data-rule="email" data-msg="Please enter a valid email" />
                  
                </div>
              </div>

           
              <div class="form-group">
                <textarea class="form-control" name="message" id="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
                
              </div>
              

              <div class="text-center"><button type="submit" onclick="sendOrder()" value="Send An Email" name="send" >Order</button></div>
              

              



        </form>


       </div> 

       

        
      </div>

      
    </section><!-- End Order Details Section -->

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">

    

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-4 col-md-6 footer-contact">
            <h3>ABZ AUTOMATIONS<span>.</span></h3>
            <p>K. N. U. S. T, <br>
                Kumasi Business Incubator, Kumasi.<br>
                Ghana <br>
                AK-315-2929<br><br></p>
              <strong>Phone:</strong> +233 50 159 1370<br>
              <strong>Email:</strong> abzautomations@gmail.com<br>
            </p>
          </div>

          <div class="col-lg-4 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:home' %}">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:home' %}#about">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:home' %}#products-and-services">Services</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:home' %}#products">Products</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:home' %}#pricing">Pricing</a></li>
            </ul>
          </div>

          

          <div class="col-lg-4 col-md-6 footer-links">
            <h4>Our Social Networks</h4>
            <p>Follow Us On Our Social Media Pages</p>
            <div class="social-links mt-3">
              <a href="https://twitter.com/abz_automations" target="_blank" rel="noopener noreferrer" class="twitter"><i class="bx bxl-twitter"></i></a>
              <a href="https://web.facebook.com/1Abzautomations" target="_blank" rel="noopener noreferrer" class="facebook"><i class="bx bxl-facebook"></i></a>
              <a href="https://www.instagram.com/abz_automations/" target="_blank" class="instagram"><i class="bx bxl-instagram"></i></a>
              <a href="https://www.youtube.com/channel/UClOn2TaH7U78kf0NlVFLRZg" target="_blank" rel="noopener noreferrer" class="google-plus"><i class="bx bxl-youtube"></i></a>
              <a href="https://www.linkedin.com/company/19127501/" target="_blank" rel="noopener noreferrer" class="linkedin"><i class="bx bxl-linkedin"></i></a>
              <a href="https://Wa.me/+233501591370" target="_blank" rel="noopener noreferrer" class="whatsapp"><i class="bx bxl-whatsapp"></i></a>
            </div>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="container py-4">
      <div class="copyright">
        &copy; Copyright <strong><span>ABZ AUTOMATIONS</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
       
      </div>
    </div>
  </footer><!-- End Footer -->


  
  <div id="preloader"></div>
  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>



  <script type="text/javascript">
        function sendOrder() {
            var name = $("#name");
            var email = $("#email");
            var location = $("#location");
            var phone = $("#phone");
            var model = $("#model");
            var image = $("#image");
            var tank = $("#tank");
            var pump = $("#pump");
            var message = $("#message");

            if (isNotEmpty(name) && isNotEmpty(email) && isNotEmpty(location) && isNotEmpty(phone) && isNotEmpty(model) && isNotEmpty(tank) && isNotEmpty(pump) && isNotEmpty(message)) {
                $.ajax({
                   url: 'send{% url 'website:order' %}',
                   method: 'POST',
                   dataType: 'json',
                   data: {
                       name: name.val(),
                       email: email.val(),
                       location: location.val(),
                       phone: phone.val(),
                       model: model.val(),
                       image: image.val(),
                       tank: tank.val(),
                       pump: pump.val(),
                       message: message.val()
                   }, success: function (response) {
                        if (response.status == "success")
                            alert('Email Has Been Sent! Thanks for contacting ABZ AUTOMATIONS, you will hear from us soon.');
                        else {
                            alert('Please Try Again!');
                            console.log(response);
                        }
                   }
                });
            }
        }

        function isNotEmpty(caller) {
            if (caller.val() == "") {
                caller.css('border', '1px solid red');
                return false;
            } else
                caller.css('border', '');

            return true;
        }
    </script>



  <!-- Vendor JS Files -->
  <script src="{% static 'website/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'website/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'website/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'website/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'website/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'website/vendor/counterup/counterup.min.js' %}"></script>
  <script src="{% static 'website/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'website/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'website/vendor/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'website/vendor/aos/aos.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'website/js/main.js' %}"></script>

</body>

</html>